os:
- linux

language: php

cache:
  directories:
  - "$HOME/.phive"
  - "$HOME/.phive/phars"
  - "$HOME/.cache/composer"
  - "$HOME/.composer/cache"
  - "$HOME/.gnupg"

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.3
  - 7.0snapshot
  - 7.1snapshot
  - 7.2snapshot
  - 7.3snapshot
  - master

before_install:
  - if [ ! -d $HOME/.phive ]; then mkdir $HOME/.phive ; fi
  - if [ ! -f $HOME/.phive/phive.phar ]; then ant getphive ; mv phive.phar $HOME/.phive ; fi
  - sudo cp $HOME/.phive/phive.phar /usr/local/bin/phive

before_script:
  - travis_retry composer install --no-interaction --prefer-source
  - phive --no-progress install --trust-gpg-keys 4AA394086372C20A,2A8299CE842DD38C,96AFE5FD66ED915A
  - ant phpab

script: ./tools/phpunit

matrix:
  allow_failures:
    - php: master
  fast_finish: true

notifications:
  email: false
