os:
- linux

language: php

cache:
  directories:
  - "$HOME/.phive"
  - "$HOME/.phive/phars"
  - "$HOME/.cache/composer"
  - "$HOME/.composer/cache"
  - "$HOME/.gnupg"

php:
  - 7.2
  - 7.3
  - 7.4
  - 7.2snapshot
  - 7.3snapshot
  - 7.4snapshot
  - master

before_script:
  - sudo apt-get install ant
  - travis_retry composer install --no-interaction --prefer-source
  - ant install-tools-ci
  - ant phpab

script: ./tools/phpunit

matrix:
  allow_failures:
    - php: master
  fast_finish: true

notifications:
  email: false
